name: Job Scraper Workflow

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  scrape-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Chrome and Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb google-chrome-stable

      - name: Setup ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          curl -L -o chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium tweepy python-dotenv
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Display Chrome and ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Scrape job posts
        run: |
          python linkedin_scraper.py

      - name: Post jobs to twitter
        run: |
          python job_post.py
